"""Regenerate ``SPEC_ALL_COMBINED.md`` from the individual spec files.

The combined file says "Do not edit this file directly" and, until now, nothing
enforced that. It drifted: SPEC_10 was rewritten for the v2.1 serving formats
while the combined copy still described the GGUF matrix, so the repo held two
contradictory answers to "what does quantize produce" and both looked official.

Run after editing any spec:

    python -m scripts.combine_specs --write

``tests/test_repo_contracts.py`` runs it in check mode, so a stale combined file
fails CI rather than being discovered by someone reading the wrong one.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "Documentation" / "Implementation MDs"
COMBINED = SPECS / "SPEC_ALL_COMBINED.md"

HEADER = (
    "# All implementation specs, combined\n"
    "\n"
    "Generated from the individual SPEC files. Do not edit this file directly.\n"
    "\n"
)


def spec_files() -> list[Path]:
    """Every individual spec, in order. Archived copies are excluded."""
    return sorted(
        p for p in SPECS.glob("SPEC_*.md")
        if p.name != COMBINED.name and "_archive" not in str(p)
    )


def render() -> str:
    parts = [HEADER]
    for path in spec_files():
        parts.append(
            f"\n---\n\n# {path.stem}\n\n{path.read_text(encoding='utf-8').rstrip()}\n"
        )
    return "".join(parts)


def drifted() -> bool:
    """Whether the combined file no longer matches its sources."""
    if not COMBINED.exists():
        return True
    return COMBINED.read_text(encoding="utf-8") != render()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the combined spec")
    parser.add_argument("--write", action="store_true", help="write the file rather than checking")
    args = parser.parse_args(argv)

    if args.write:
        COMBINED.write_text(render(), encoding="utf-8")
        print(f"wrote {COMBINED.relative_to(ROOT)} from {len(spec_files())} spec files")
        return 0

    if drifted():
        print(
            f"{COMBINED.name} is stale. Regenerate with "
            "`python -m scripts.combine_specs --write` — never hand-edit it.",
            file=sys.stderr,
        )
        return 1
    print(f"{COMBINED.name} is up to date")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
